[package]
name = "mr-cool-nes"
version = "0.1.0"
authors = ["nukeop <nukeop@gumblert.tech>"]

[dependencies]
clap = "2.32.0"
config = "0.9.0"
log = "0.4.0"
pretty_env_logger = "0.2.4"

[dependencies.sdl2]
version = "0.31.0"
features = ["image"]